delete DBeli
delete DJual
delete HBeli
delete HJual
delete DReturBeli
delete DReturJual
delete HReturBeli
delete HReturJual
delete TbBarang
delete TbKontakSupplier
delete TbSatuan
delete DSatuan
delete TbStaff
delete TbSupplier